import { env } from "cloudflare:workers";
import { getChatGPTUser } from "../../../chatgpt-auth";
import { stripeConfig, type BillingMode } from "../../../lib/billing-config";
export const dynamic="force-dynamic";
type StripeProduct={id:string;name:string;description?:string|null;active:boolean;metadata?:Record<string,string>};
type StripePrice={id:string;product:string;active:boolean;unit_amount:number|null;currency:string;recurring?:{interval:string;interval_count:number}|null;lookup_key?:string|null};
async function admin(){const user=await getChatGPTUser();if(!user)return null;return await env.DB.prepare("SELECT role FROM platform_admins WHERE email=?").bind(user.email).first()?user:null}
async function stripe(mode:BillingMode,path:string,method="GET",values?:Record<string,string>){const config=await stripeConfig(mode);if(!config.key)throw new Error(`${mode} Stripe secret key is not configured.`);const response=await fetch(`https://api.stripe.com/v1/${path}`,{method,headers:{authorization:`Bearer ${config.key}`,"content-type":"application/x-www-form-urlencoded","Stripe-Version":"2026-07-29.dahlia"},body:values?new URLSearchParams(values):undefined});const result=await response.json() as {data?:unknown[];error?:{message?:string}}&Record<string,unknown>;if(!response.ok)throw new Error(result.error?.message||"Stripe request failed.");return result}
export async function GET(request:Request){if(!await admin())return Response.json({error:"Unauthorized"},{status:401});const mode=(new URL(request.url).searchParams.get("mode")==="live"?"live":"test") as BillingMode;try{const [products,prices]=await Promise.all([stripe(mode,"products?limit=100"),stripe(mode,"prices?limit=100&type=recurring")]);const list=(products.data||[]) as StripeProduct[];const priceList=(prices.data||[]) as StripePrice[];return Response.json({mode,products:list.map(product=>({...product,prices:priceList.filter(price=>price.product===product.id)}))})}catch(error){return Response.json({error:error instanceof Error?error.message:"Could not load Stripe products."},{status:502})}}
export async function POST(request:Request){const user=await admin();if(!user)return Response.json({error:"Unauthorized"},{status:401});const body=await request.json().catch(()=>null) as {mode?:BillingMode;name?:string;description?:string;amount?:number;currency?:string;planCode?:string}|null;if(!body?.name||!body.amount||body.amount<50)return Response.json({error:"Name and a valid monthly price are required."},{status:400});const mode=body.mode==="live"?"live":"test";try{const product=await stripe(mode,"products","POST",{name:body.name,description:body.description||"","metadata[pollrr_plan_id]":body.planCode||"custom"}) as unknown as StripeProduct;const slug=(body.planCode||body.name).toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"").slice(0,40);const price=await stripe(mode,"prices","POST",{product:product.id,unit_amount:String(Math.round(body.amount)),currency:body.currency||"usd","recurring[interval]":"month","lookup_key":`pollrr_${slug}_monthly`});return Response.json({product,price})}catch(error){return Response.json({error:error instanceof Error?error.message:"Could not create Stripe product."},{status:502})}}
export async function PATCH(request:Request){if(!await admin())return Response.json({error:"Unauthorized"},{status:401});const body=await request.json().catch(()=>null) as {mode?:BillingMode;id?:string;name?:string;description?:string;planCode?:string;amount?:number;currentPriceId?:string}|null;if(!body?.id||!body.name)return Response.json({error:"Product and name are required."},{status:400});const mode=body.mode==="live"?"live":"test";try{const product=await stripe(mode,`products/${encodeURIComponent(body.id)}`,"POST",{name:body.name,description:body.description||"","metadata[pollrr_plan_id]":body.planCode||"custom"});if(body.amount&&body.amount>=50){const slug=(body.planCode||body.name).toLowerCase().replace(/[^a-z0-9]+/g,"_").replace(/^_|_$/g,"").slice(0,40);if(body.currentPriceId)await stripe(mode,`prices/${encodeURIComponent(body.currentPriceId)}`,"POST",{active:"false"});await stripe(mode,"prices","POST",{product:body.id,unit_amount:String(Math.round(body.amount)),currency:"usd","recurring[interval]":"month","lookup_key":`pollrr_${slug}_monthly`,"transfer_lookup_key":"true"})}return Response.json({product})}catch(error){return Response.json({error:error instanceof Error?error.message:"Could not update Stripe product."},{status:502})}}
export async function DELETE(request:Request){if(!await admin())return Response.json({error:"Unauthorized"},{status:401});const url=new URL(request.url);const id=url.searchParams.get("id");const mode=url.searchParams.get("mode")==="live"?"live":"test";if(!id)return Response.json({error:"Product is required."},{status:400});try{const prices=await stripe(mode,`prices?product=${encodeURIComponent(id)}&limit=100`) as {data?:StripePrice[]};await Promise.all((prices.data||[]).filter(p=>p.active).map(p=>stripe(mode,`prices/${encodeURIComponent(p.id)}`,"POST",{active:"false"})));await stripe(mode,`products/${encodeURIComponent(id)}`,"POST",{active:"false"});return Response.json({archived:true})}catch(error){return Response.json({error:error instanceof Error?error.message:"Could not archive Stripe product."},{status:502})}}
