import { env } from "cloudflare:workers";
import { PLANS, type PlanId } from "../../../lib/plans";
import { stripeConfig } from "../../../lib/billing-config";
export const dynamic="force-dynamic";
type StripeObject={id?:string;customer?:string;subscription?:string;client_reference_id?:string;status?:string;current_period_end?:number;cancel_at_period_end?:boolean;metadata?:{billing_reference?:string;plan_id?:string}};
type StripeEvent={id:string;type:string;livemode:boolean;data:{object:StripeObject}};
function hex(bytes:ArrayBuffer){return [...new Uint8Array(bytes)].map(value=>value.toString(16).padStart(2,"0")).join("")}
function safeEqual(a:string,b:string){if(a.length!==b.length)return false;let value=0;for(let i=0;i<a.length;i++)value|=a.charCodeAt(i)^b.charCodeAt(i);return value===0}
async function verify(payload:string,header:string,secret:string){const values:Record<string,string[]>={};for(const part of header.split(",")){const [key,value]=part.split("=",2);if(key&&value)(values[key]||=[]).push(value)}const timestamp=Number(values.t?.[0]);if(!timestamp||!values.v1?.length||Math.abs(Date.now()/1000-timestamp)>300)return false;const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(secret),{name:"HMAC",hash:"SHA-256"},false,["sign"]);const expected=hex(await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(`${timestamp}.${payload}`)));return values.v1.some(signature=>safeEqual(expected,signature))}
async function digest(value:string){return hex(await crypto.subtle.digest("SHA-256",new TextEncoder().encode(value)))}
export async function POST(request:Request){
 const payload=await request.text();let event:StripeEvent;try{event=JSON.parse(payload) as StripeEvent}catch{return Response.json({error:"Invalid event."},{status:400})}const mode=event.livemode?"live":"test";const secret=(await stripeConfig(mode)).webhook;if(!secret)return Response.json({error:`Stripe ${mode} webhook is not configured.`},{status:503});if(!await verify(payload,request.headers.get("stripe-signature")||"",secret))return Response.json({error:"Invalid signature."},{status:400});
 const object=event.data.object;const reference=object.metadata?.billing_reference||object.client_reference_id||"";const member=reference?await env.DB.prepare("SELECT email FROM creator_memberships WHERE billing_reference=?").bind(reference).first<{email:string}>():null;const email=member?.email||"";const rawPlan=object.metadata?.plan_id||"";const planId=(rawPlan in PLANS?rawPlan:"free") as PlanId;
 const inserted=await env.DB.prepare("INSERT OR IGNORE INTO billing_events (id,provider,provider_event_id,event_type,email,plan_id,payload_hash,created_at,mode) VALUES (?,'stripe',?,?,?,?,?,?,?) RETURNING id").bind(crypto.randomUUID(),event.id,event.type,email||null,planId,await digest(payload),Date.now(),mode).first();if(!inserted)return Response.json({received:true,duplicate:true});
 if(email&&event.type==="checkout.session.completed")await env.DB.prepare("UPDATE creator_memberships SET plan_id=?,status='active',billing_provider='stripe',provider_customer_id=?,provider_subscription_id=?,requested_plan_id=NULL,updated_at=? WHERE email=?").bind(planId,object.customer||null,object.subscription||null,Date.now(),email).run();
 if(email&&(event.type==="customer.subscription.updated"||event.type==="customer.subscription.deleted")){const active=event.type!=="customer.subscription.deleted"&&["active","trialing"].includes(object.status||"");await env.DB.prepare("UPDATE creator_memberships SET plan_id=?,status=?,provider_customer_id=COALESCE(?,provider_customer_id),provider_subscription_id=?,current_period_end=?,cancel_at_period_end=?,updated_at=? WHERE email=?").bind(active?planId:"free",active?"active":"cancelled",object.customer||null,object.id||null,(object.current_period_end||0)*1000,object.cancel_at_period_end?1:0,Date.now(),email).run()}
 return Response.json({received:true});
}
