import { env } from "cloudflare:workers";
import { getChatGPTUser } from "../../chatgpt-auth";
import { PLANS, planFor, type PlanId } from "../../lib/plans";
import { activeStripeConfig } from "../../lib/billing-config";
export const dynamic="force-dynamic";
type BillingEnv={BILLING_INTELLIGENCE_CONTACT_URL?:string};
const INTEGRATION_IDENTIFIER="pollrr_checkout_qjtmvxka";
function httpsUrl(value?:string){if(!value)return null;try{const url=new URL(value);return url.protocol==="https:"?url:null}catch{return null}}
async function stripe(path:string,secret:string,values:Record<string,string>){const response=await fetch(`https://api.stripe.com/v1/${path}`,{method:"POST",headers:{authorization:`Bearer ${secret}`,"content-type":"application/x-www-form-urlencoded","Stripe-Version":"2026-07-29.dahlia"},body:new URLSearchParams(values)});const result=await response.json() as {url?:string;error?:{message?:string}};if(!response.ok)throw new Error(result.error?.message||"Stripe could not create the billing session.");return result}
async function activePlanPrice(secret:string,plan:"pro"|"studio",fallback?:string){const response=await fetch(`https://api.stripe.com/v1/prices?active=true&limit=1&lookup_keys[]=${encodeURIComponent(`pollrr_${plan}_monthly`)}`,{headers:{authorization:`Bearer ${secret}`,"Stripe-Version":"2026-07-29.dahlia"}});if(!response.ok)return fallback;const result=await response.json() as {data?:{id:string}[]};return result.data?.[0]?.id||fallback}
async function membership(email:string){return env.DB.prepare("SELECT plan_id,status,billing_provider,provider_customer_id,current_period_end,cancel_at_period_end,requested_plan_id,billing_reference FROM creator_memberships WHERE email=?").bind(email).first<Record<string,unknown>>()}
export async function GET(){const user=await getChatGPTUser();if(!user)return Response.json({error:"Unauthorized"},{status:401});const billing=await activeStripeConfig();const current=await membership(user.email);return Response.json({membership:current||{plan_id:"free",status:"active"},billingMode:billing.mode,processorReady:Boolean(billing.key&&billing.pro&&billing.studio),portalReady:Boolean(billing.key&&current?.provider_customer_id)})}
export async function POST(request:Request){
 const user=await getChatGPTUser();if(!user)return Response.json({error:"Unauthorized"},{status:401});const body=await request.json().catch(()=>null) as {action?:string;planId?:PlanId}|null;let current=await membership(user.email);const billing=await activeStripeConfig();const e=env as typeof env&BillingEnv;const origin=new URL(request.url).origin;
 if(body?.action==="portal"){if(!billing.key||!current?.provider_customer_id)return Response.json({error:"Billing portal is not available for this account yet.",setupRequired:true},{status:503});try{const session=await stripe("billing_portal/sessions",billing.key,{customer:String(current.provider_customer_id),return_url:`${origin}/studio?start=plans`});return Response.json({url:session.url})}catch(error){return Response.json({error:error instanceof Error?error.message:"Could not open billing."},{status:502})}}
 if(body?.action!=="checkout"||!body.planId||!(body.planId in PLANS))return Response.json({error:"Choose a valid plan."},{status:400});const plan=planFor(body.planId);const now=Date.now();if(plan.id==="free")return Response.json({active:true,planId:current?.plan_id||"free"});
 await env.DB.prepare(`INSERT INTO creator_memberships (email,plan_id,status,requested_plan_id,billing_reference,created_at,updated_at) VALUES (?,'free','active',?,?,?,?) ON CONFLICT(email) DO UPDATE SET requested_plan_id=excluded.requested_plan_id,billing_reference=COALESCE(creator_memberships.billing_reference,excluded.billing_reference),updated_at=excluded.updated_at`).bind(user.email,plan.id,crypto.randomUUID().replaceAll("-",""),now,now).run();current=await membership(user.email);
 if(plan.id==="intelligence"){const contact=httpsUrl(e.BILLING_INTELLIGENCE_CONTACT_URL);return contact?Response.json({url:contact.toString()}):Response.json({setupRequired:true,requestedPlan:plan.id,message:"Your Intelligence request is saved. Pollrr will contact you when enterprise onboarding opens."},{status:202})}
 if(!billing.key)return Response.json({setupRequired:true,requestedPlan:plan.id,message:`Your plan choice is saved. ${billing.mode} checkout is not configured yet.`},{status:202});const price=await activePlanPrice(billing.key,plan.id as "pro"|"studio",plan.id==="pro"?billing.pro:billing.studio);if(!price)return Response.json({setupRequired:true,requestedPlan:plan.id,message:`Create an active ${plan.name} monthly price in the ${billing.mode} Stripe catalog.`},{status:202});
 try{const reference=String(current?.billing_reference);const values:Record<string,string>={mode:"subscription","line_items[0][price]":price,"line_items[0][quantity]":"1",client_reference_id:reference,"metadata[billing_reference]":reference,"metadata[plan_id]":plan.id,"subscription_data[metadata][billing_reference]":reference,"subscription_data[metadata][plan_id]":plan.id,success_url:`${origin}/studio?start=plans&checkout=success`,cancel_url:`${origin}/studio?start=plans&checkout=cancelled`,allow_promotion_codes:"true",integration_identifier:INTEGRATION_IDENTIFIER};if(current?.provider_customer_id)values.customer=String(current.provider_customer_id);else if(!user.email.endsWith("@creator.pollrr"))values.customer_email=user.email;const session=await stripe("checkout/sessions",billing.key,values);return Response.json({url:session.url})}catch(error){return Response.json({error:error instanceof Error?error.message:"Could not start checkout."},{status:502})}
}
